# Generated by Django 2.0.3 on 2018-09-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('toppings', 'Toppings'), ('pizza_regular', 'Regular Pizza'), ('salads', 'Salads'), ('dinner_platters', 'Dinner Platters'), ('pasta', 'Pasta'), ('subs', 'Subs'), ('pizza_sicilian', 'Sicilian Pizza')], max_length=30),
        ),
    ]
