# Generated by Django 2.0.3 on 2018-09-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180902_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('type', models.CharField(choices=[('dinner_platters', 'Dinner Platters'), ('pasta', 'Pasta'), ('subs', 'Subs'), ('pizza_sicilian', 'Sicilian Pizza'), ('pizza_regular', 'Regular Pizza'), ('salads', 'Salads'), ('toppings', 'Toppings')], max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
