# Generated by Django 2.0.3 on 2018-09-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180902_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='product',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='product',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('pizza_sicilian', 'Sicilian Pizza'), ('salads', 'Salads'), ('pasta', 'Pasta'), ('dinner_platters', 'Dinner Platters'), ('pizza_regular', 'Regular Pizza'), ('toppings', 'Toppings'), ('subs', 'Subs')], max_length=30),
        ),
    ]
