# Generated by Django 2.0.3 on 2018-09-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180902_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('type', models.CharField(choices=[('pasta', 'Pasta'), ('pizza_sicilian', 'Sicilian Pizza'), ('pizza_regular', 'Regular Pizza'), ('subs', 'Subs'), ('toppings', 'Toppings'), ('dinner_platters', 'Dinner Platters'), ('salads', 'Salads')], max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
