# Generated by Django 2.0.3 on 2018-09-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180902_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('toppings', 'Toppings'), ('pasta', 'Pasta'), ('pizza_regular', 'Regular Pizza'), ('dinner_platters', 'Dinner Platters'), ('subs', 'Subs'), ('salads', 'Salads'), ('pizza_sicilian', 'Sicilian Pizza')], max_length=30),
        ),
    ]
