# Generated by Django 2.0.3 on 2018-09-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180902_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('large', 'Large')], default='Small', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('salads', 'Salads'), ('dinner_platters', 'Dinner Platters'), ('subs', 'Subs'), ('pizza_sicilian', 'Sicilian Pizza'), ('pizza_regular', 'Regular Pizza'), ('toppings', 'Toppings'), ('pasta', 'Pasta')], max_length=30),
        ),
    ]
