# Generated by Django 2.0.3 on 2018-09-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180902_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='size',
            field=models.CharField(choices=[('large', 'Large'), ('small', 'Small')], max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('subs', 'Subs'), ('pizza_regular', 'Regular Pizza'), ('pizza_sicilian', 'Sicilian Pizza'), ('pasta', 'Pasta'), ('salads', 'Salads'), ('toppings', 'Toppings'), ('dinner_platters', 'Dinner Platters')], max_length=30),
        ),
    ]
