# Generated by Django 2.0.3 on 2018-09-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180902_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('large', 'Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('pizza_regular', 'Regular Pizza'), ('subs', 'Subs'), ('salads', 'Salads'), ('dinner_platters', 'Dinner Platters'), ('pasta', 'Pasta'), ('pizza_sicilian', 'Sicilian Pizza'), ('toppings', 'Toppings')], max_length=30),
        ),
    ]
