# Generated by Django 2.0.3 on 2018-09-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180902_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='size',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price_large',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price_small',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('dinner_platters', 'Dinner Platters'), ('pizza_sicilian', 'Sicilian Pizza'), ('pasta', 'Pasta'), ('pizza_regular', 'Regular Pizza'), ('toppings', 'Toppings'), ('salads', 'Salads'), ('subs', 'Subs')], max_length=30),
        ),
    ]
