# Generated by Django 2.0.3 on 2018-09-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180902_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('salads', 'Salads'), ('subs', 'Subs'), ('pizza_regular', 'Regular Pizza'), ('dinner_platters', 'Dinner Platters'), ('pizza_sicilian', 'Sicilian Pizza'), ('toppings', 'Toppings'), ('pasta', 'Pasta')], max_length=30)),
                ('item', models.CharField(max_length=45)),
                ('price_small', models.FloatField(blank=True, null=True)),
                ('price_large', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
