# Generated by Django 2.0.3 on 2018-09-19 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20180919_0110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
